[package]
name = "developer-challenge"
version = "0.1.0"
authors = ["Dylan McGannon <me@dyl.dog>"]
edition = "2018"

[dependencies]
csv = "1"
regex = "1"
lazy_static = "1.2.0"
rpn = "0.1.0"
itertools = "0.8.0"
petgraph = "0.4.13"